### ISSUE TITLE
Call to undefined function Rennokki\Larafy\Traits\now()

### ISSUE THREAD

**Issue by alibaraneser** [rennokki/larafy#10]
Hey,

I'm getting this error, 

Call to undefined function Rennokki\Larafy\Traits\now()
--
 
Codes,

> $api = new Larafy();
>         try {
>             $api->searchArtists('Lana del Rey', -30, -40);
>         } catch(\Rennokki\Larafy\Exceptions\SpotifyAPIException $e) {
>             // invalid data sent
>             $e->getAPIResponse(); // Get the JSON API response.
>         }

**Comment by rennokki** [comment]
Hey @alibaraneser,

Basically, this happens because you don't work with Laravel, but this package was initially created for Laravel. Hope this will be the fix for non-Laravel users.
It's a fix on the way 😄

**Comment by rennokki** [comment]
Just pushed out the 1.0.3 version. Thank you for the bug report ❤️
