### ISSUE TITLE
Add UserTrait

### ISSUE THREAD

**Issue by patrickpietens** [rennokki/larafy#8]
Hey man,

Looking at your library I'm missing the user endpoints. Are you planning to write those in the near future? If not, I'm gladly willing to help you with this.

Let me know!

**Comment by rennokki** [comment]
@patrickpietens It has been a week full of me, i barely reached my email these days (while i usually check them daily).

The changes look good, the methods used in requests have been drastically improved on what means "disposable code". I really love it! 😄 

I'll have to pull some readme updates for this asap. I'll open the PR for you.

**Comment by patrickpietens** [comment]
@rennokki Hey man,

A quick heads up:

I'm still making changes to the source code. I've added config files and binding the Larafy class to Laravel's service container.

**Comment by hugosav** [comment]
@patrickpietens @rennokki  I was also working to add userTrait and other missing parts, I'm highly interested in using your work and even collaborate. Looking forward the merge of both repos.

awesome job both of you !

**Comment by patrickpietens** [comment]
@hugosav Love to do a collab!

**Comment by rennokki** [comment]
That seems like I have to rethink some implementations, but not for now. 😞

**Comment by patrickpietens** [comment]
@rennokki In that case I will hard fork the repo and continue the project on my own. Thnx for your help.
